### PR TITLE
Feature/160 - Reform accordion panel

### PR DESCRIPTION
**Pull request by tiiavalt**
See issue #160 
This PR's commits should be squashed into one when merging.

### CODE REVIEW

**Comment by turso** [comment]
There is some codacy issue here. I'm not sure is it a valid one but @tiiavalt what do you think?

**Review by turso — APPROVED** [review]

**Comment by tiiavalt** [comment]
Honestly, I have no idea what it means by complexity. I've tried to count the function's complexity, but can't understand where they get their complexity number from. 
What comes to "Generic Object Injection Sink", I'm clueless with that one too 😅

**Comment by turso** [comment]
Also after the previous merges there are conflicts. Could you resolve them?

We should check those Codacy rules as some of them are plain simple stupid.

**Comment by tiiavalt** [comment]
Sure! I fixed some of them, but didn't see there were new ones. They're fixed now.

**Pull request merged**
